


use std::{cell::RefCell, collections::HashMap};


use super::{ast::{self, BinOp, GenericArgDefinition, GenericsConstraint, ItemPath, TokenRange, UnOp}, Attribute, InternedString, StorageClass, Uniformity};




/// Resolved item paths are global paths where generics information is already resolved and included
/// in the path via name mangling. The path as a whole is then joined with "::" and forms the resolved path.
pub struct ResolvedItemPath(pub InternedString);


#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct SymbolID(pub usize);


pub struct SymbolTable {
    path: InternedString,
    map: HashMap<InternedString, usize>,
    items: Vec<GlobalItem>,
}


impl SymbolTable {
    pub fn new(path: InternedString) -> Self {
        Self {
            path,
            map: HashMap::with_capacity(1024),
            items: Vec::with_capacity(1024),
        }
    }
    
    pub fn path(&self) -> InternedString {
        self.path
    }
    
    
    pub fn lookup(&self, path: &InternedString) -> Option<&GlobalItem> {
        self.map.get(path).and_then(|i| Some(&self.items[*i]))
    }
    
    pub fn insert(&mut self, path: InternedString, item: GlobalItem) -> Result<(), ()> {
        if let Some(i) = self.map.get(&path) {
            return Err(());
        }
        let i = self.items.len();
        self.items.push(item);
        self.map.insert(path, i);
        return Ok(());
    }
    
    pub fn replace_symbol(&mut self, id: SymbolID, item: GlobalItem) {
        self.items[id.0] = item;
    }
    
}


pub enum GlobalItem {
    /// Generic struct. Should be resolved after type checking and can then be ignored.
    StructTemplate {
        args: Vec<GenericArgDefinition>,
        constraints: Vec<GenericsConstraint>,
    },
    Struct {
        attrs: Vec<Attribute>,
        ident_token: TokenRange,
        
    },
    Trait {
        attrs: Vec<Attribute>,
        ident_token: TokenRange,
        args: Vec<GenericArgDefinition>,
        constraints: Vec<GenericsConstraint>,
        types: Vec<InternedString>,
        /// Trait functions contain no blocks, only implementation functions do.
        functions: Vec<Function>,
    },
    Static {
        
    },
    FunctionTemplate {
        
        args: Vec<GenericArgDefinition>,
        constraints: Vec<GenericsConstraint>,
    },
    Function(Function),
    Import {
        public: bool,
        path: ItemPath,
    },
    // TODO import from another symbol table, to make symbol tables for packages more disposable for an LSP.
    ResolvedImport {
        public: bool,
        path: ItemPath,
        id: SymbolID,
    },
    
    /// The global vector type. The actual data is in the corresponding Type enum.
    Vector,
    /// The global vector type. The actual data is in the corresponding Type enum.
    Matrix,
    Array,
    RuntimeArray,
    
    
}


pub struct Function {
    pub attrs: Vec<Attribute>,
    pub ident_token: TokenRange,
    pub params: Vec<(InternedString, TokenRange, Type)>,
    pub ret: Type,
    pub blocks: RefCell<Vec<IRBlock>>,
}


#[derive(Debug, Clone)]
pub struct Type {
    /// Irrelevant or to-be-inferred uniformity.
    pub uni: Option<Uniformity>,
    pub var: TypeVariant,
}

#[derive(Debug, Clone)]
pub enum TypeVariant {
    Unresolved(ItemPath),
    /// Only valid for concrete structs and traits. Should be generated by the type checking stage via monomorphisation.
    Resolved(SymbolID, TokenRange),
    Primitive(Primitive),
    Vector {
        components: u8,
        ty: Primitive,
    },
    Matrix {
        rows: u8,
        cold: u8,
        ty: Primitive,
    },
    Array {
        length: usize,
        ty: Box<Type>,
    },
    RuntimeArray {
        ty: Box<Type>,
    },
    Pointer {
        class: StorageClass,
        ty: Box<Type>,
    }
}

#[derive(Debug, Clone)]
pub enum Primitive {
    U8, U16, U32, U64,
    I8, I16, I32, I64,
    F16, F32, F64,
    Bool,
    Unit
}



#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct IRID(pub usize);

/// A small SSA instruction set.
pub enum IRInstruction {
    /// An unresolved path. Should be eliminated by path canonicalization.
    /// Can be turned either into a ResolvedPath or eliminated via replacing with the local SSA ID.
    Path {
        path: ItemPath,
        tokens: TokenRange,
        id: IRID,
    },
    
    /// A path that has been resolved into a global symbol ID.
    /// Only functions and statics can be used like this.
    /// Type information is stored in the symbol.
    ResolvedPath {
        path: SymbolID,
        token: TokenRange,
        id: IRID,
    },
    
    Local {
        ident: InternedString,
        ident_token: TokenRange,
        id: IRID,
        /// None for a type to be inferred.
        ty: Option<Type>,
    },
    
    // TODO trait method invocation
    
    
    UnOp {
        inp: IRID,
        op: UnOp,
        out: IRID,
        span: TokenRange,
        // no type, unary and binary operators have the same input as output types, except assignment (which has Unit).
    },
    
    BinOp {
        lhs: IRID,
        op: BinOp,
        rhs: IRID,
        out: IRID,
        span: TokenRange,
        // no type, unary and binary operators have the same input as output types, or a predefined output (bool for comparisons), except assignment (which has Unit).
    },
    
    Property {
        inp: IRID,
        name: (InternedString, TokenRange),
        out: IRID,
        // No type, can be read from the type of the input and the field
    },
    
    Call {
        func: IRID,
        args: Vec<IRID>,
        out: IRID,
        span: TokenRange,
    },
    
    Int {
        v: u128,
        id: IRID,
        token_id: TokenRange,
        /// None for a type to be inferred.
        ty: Option<Type>,
    },
    
    Float {
        v: f64,
        id: IRID,
        token_id: TokenRange,
        /// None for a type to be inferred.
        ty: Option<Type>,
    },
    
    
    Cast {
        inp: IRID,
        out: IRID,
        ty: Type,
    },
    
    
    SelectionMerge {
        block: usize,
        construct: TokenRange,
    },
    LoopMerge {
        block: usize,
        construct: TokenRange,
    },
    Branch {
        target_block: usize,
    },
    BranchConditional {
        inp: IRID,
        true_target_block: usize,
        false_target_block: usize,
    },
    
    
}

pub struct IRBlock {
    pub instructions: Vec<IRInstruction>,
}






