# The "rsl-test" table is how the test runner recognizes a config file and is required.
[rsl-test]

# TODO config file format for graphics pipeline tests?

# This can either be a path to a source file or a precompiled SPIR-V shader.
# In case a source file is specified, the RSL compiler has to be present, as well as the Vulkan SDK.
# Precompiled SPIR-V files (compiled with the debug flag) can be run without further tooling.
# The files are recognized by the SPIR-V magic number, both normal and reverse (for other endianness).
shader = "shader.spv"

# The reflection output of the compiler. Has to be present when a "member" key is used in the overrides table.
# reflection = "reflection.json"

# These optional fields set the content of the push constant range
# push.data = "buffer3"
# push.offset = 0


[[specialisation]]
# Index of the specialisation constant or start index in case of a vector constant
index = 0
# The value of the constant. Can be true, false, a number of an array of numbers of length 2 to 4 (which forms a vector).
# The type is checked with the SPIR-V binary.
value = 12.5



# This table contains the paths of binary blobs that are assigned to images and buffers. They have to be in the correct format.
# Pointer members of structs should be zeroed and replaced in a later section.
[blobs]

buffer1 = "blobs/buffer1"
buffer2 = "blobs/buffer2"



# This table allows for overriding data in blobs before passing it the the shader, to insert physical pointers of buffers
[[overrides]]
# TODO allow other overrides and overrides via CLI arguments, to make testing multiple cases easier without generating lots of config files.

# The blob to modify
blob = "buffer1"

# The pointer to insert
reference = "buffer2"

# One of the 2 optional fields is required
# TODO is supporting the offset variant actually useful?

# The offset in the buffer to start replacing
# offset = 0

# The name of the struct member to replace with the pointer
# member = "foo_ptr"

# Be aware that the runner is only able to know the type of buffers that are named as members, by looking in the reflection information.
# When you use the offset method in a pointer chain, blobs further down the cain can also only use the offset method.



# This array table assigns blob names to the binding set and binding numbers.
[[bindings]]
set = 0
binding = 0
data = "buffer1"








