#pragma once

#include <stdint.h>
#include <stddef.h>

#ifdef __cplusplus
extern "C" {
#endif


/// The current version of the RSL ABI this header supports.
#define RSL_ABI 0

/// @brief A structure containing an RSL module and its metadata.
/// 
/// This struct should not be build yourself but generated by the compiler to ensure compatibility.
typedef struct {
    /// @brief The ABI version of this struct.
    uint32_t abi_version;
    
    
    /// @brief The generated IR blob. For now this is SPIR-V, but it may become an internal IR in the future if needed.
    const uint8_t* code;
    
    /// @brief Size of the generated IR blob in bytes.
    uint32_t code_size;
    
    
    const RSLGraphicsPipeline* graphics_pipelines;
    uint32_t graphics_pipelines_length;
    
    
    const RSLFlowShader* flow_entrypoints;
    
    uint32_t flow_entrypoints_length;
    
    
} RSLModule;


typedef enum {
    RSL_PIPELINE_VERTEX,
    RSL_PIPELINE_MESH,
} RSLGraphicsPipelineType;

typedef struct  {
    RSLGraphicsPipelineType ty;
    /// Name of the pre-rasterization stage entrypoint, so the vertex or mesh shader
    const char* pre_raster;
    const char* fragment;
    
    
} RSLGraphicsPipeline;


typedef struct {
    const char* name;
    /// There should be as many entrypoints as dispatch parts, all with the name and the dispatch part number appended.
    uint32_t dispatch_parts;
    const RSLFlowShaderToken* sequence;
    uint32_t sequence_length;
    
} RSLFlowShader;



typedef enum {
    RSL_TOKEN_DISPATCH,
    RSL_TOKEN_DRAW,
} RSLFlowShaderTokenType;

typedef struct {
    RSLFlowShaderTokenType ty;
    // Depending on the type, the index is either a dispatch part index of the flow shader or the index of a graphics pipeline.
    uint32_t index;
} RSLFlowShaderToken;


typedef enum {
    /// Dispatch/draw size is a constant
    RSL_DISPATCH_CONSTANT,
    /// Dispatch/draw size is a host value
    RSL_DISPATCH_DIRECT,
    /// Dispatch/draw size is supplied via an indirect buffer in the flow shader
    RSL_DISPATCH_INDIRECT,
    /// MultiDrawIndirect, only for graphics pipelines
    RSL_DISPATCH_MDI,
    /// Dispatch via device-generated commands. TODO: Define a fallback method in case it's unsupported.
    RSL_DISPATCH_DGC,
} RSLDispatchType;







#ifdef __cplusplus
}
#endif
