#pragma once

#include <stdint.h>
#include <stddef.h>



/// @brief A structure containing an RSL module and its metadata.
/// 
/// This struct should not be build yourself but generated by the compiler to ensure compatibility.
typedef struct {
    /// @brief The generated IR blob. For now this is SPIR-V, but it may become an internal IR in the future if needed.
    const uint8_t* code;
    
    /// @brief Size of the generated IR blob in bytes.
    uint32_t code_size;
    
    
    const RSLGraphicsPipeline* graphics_pipelines;
    uint32_t graphics_pipelines_length;
    
    
    const RSLFlowShader* flow_entrypoints;
    
    uint32_t flow_entrypoints_length;
    
    
    const RSLIES* ies;
    uint32_t ies_length;
    
    
} RSLModule;


typedef struct {
    const char* names;
    uint32_t names_length;
} RSLIES;

typedef enum {
    RSL_PIPELINE_VERTEX,
    RSL_PIPELINE_MESH,
} RSLGraphicsPipelineType;

typedef struct  {
    RSLGraphicsPipelineType ty;
    /// Name of the pre-rasterization stage entrypoint, so the vertex or mesh shader
    const char* pre_raster;
    const char* fragment;
    
    
} RSLGraphicsPipeline;


typedef struct {
    const char* name;
    /// There should be as many entrypoints as dispatch parts, all with the name and the dispatch part number appended.
    uint32_t dispatch_parts;
    const RSLFlowShaderToken* sequence;
    uint32_t sequence_length;
    
} RSLFlowShader;



typedef enum {
    RSL_TOKEN_DISPATCH,
    RSL_TOKEN_DRAW,
    RSL_BARRIER,
} RSLFlowShaderTokenType;

typedef struct {
    RSLFlowShaderTokenType ty;
    // Depending on the type, the index is either a dispatch part index of the flow shader or the index of a graphics pipeline.
    union {
        uint32_t index;
        RSLBarrierInfo* barrier;
    };
} RSLFlowShaderToken;

typedef struct
{
    RSLBarrierStage src_stage;
    RSLBarrierStage dst_stage;
    RSLBarrierAccessMask src_mask;
    RSLBarrierAccessMask dst_mask;
} RSLMemoryBarrier;



typedef struct {
    RSLMemoryBarrier memory;
    const RSLImageBarrier* image_barriers;
    uint32_t image_barrier_length;
} RSLBarrierInfo;

typedef enum {
    RSL_BARRIER_STAGE_COMPUTE,
    RSL_BARRIER_STAGE_VERTEX,
    RSL_BARRIER_STAGE_FRAGMENT,
    RSL_BARRIER_STAGE_MESH,
    RSL_BARRIER_STAGE_TRANSFER,
    RSL_BARRIER_STAGE_INDIRECT_DRAW,
    RSL_BARRIER_STAGE_INDIRECT_COPY,
    RSL_BARRIER_STAGE_TRANSFER,
} RSLBarrierStage;


typedef enum {
    // For indirect draw, dispatch and copy
    RSL_BARRIER_ACCESS_MASK_INDIRECT_READ,
    RSL_BARRIER_ACCESS_MASK_INDEX_READ,
    RSL_BARRIER_ACCESS_MASK_VERTEX_READ,
    RSL_BARRIER_ACCESS_MASK_INPUT_ATTACHMENT_READ,
    // UBO and SSBO reads
    RSL_BARRIER_ACCESS_MASK_BUFFER_READ,
    // SSBO and storage image writes
    RSL_BARRIER_ACCESS_MASK_BUFFER_WRITE,
    // Access of sampled or storage images
    RSL_BARRIER_ACCESS_MASK_IMAGE_READ,
    RSL_BARRIER_ACCESS_MASK_COLOR_ATTACHMENT_READ,
    RSL_BARRIER_ACCESS_MASK_DEPTH_STENCIL_ATTACHMENT_READ,
    RSL_BARRIER_ACCESS_MASK_COLOR_ATTACHMENT_WRITE,
    RSL_BARRIER_ACCESS_MASK_DEPTH_STENCIL_ATTACHMENT_WRITE,
    RSL_BARRIER_ACCESS_MASK_TRANSFER_READ,
    RSL_BARRIER_ACCESS_MASK_TRANSFER_WRITE,
    
} RSLBarrierAccessMask;

typedef struct {
    
    
    
} RSLImageBarrier;

typedef enum {
    /// Dispatch/draw size is a constant
    RSL_DISPATCH_CONSTANT,
    /// Dispatch/draw size is a host value
    RSL_DISPATCH_DIRECT,
    /// Dispatch/draw size is supplied via an indirect buffer in the flow shader
    RSL_DISPATCH_INDIRECT,
    /// MultiDrawIndirect, only for graphics pipelines
    RSL_DISPATCH_MDI,
    /// Dispatch via device-generated commands. TODO: Define a fallback method in case it's unsupported.
    RSL_DISPATCH_DGC,
    
} RSLDispatchType;



